app:
  title: Red Hat Developer Hub
  baseUrl: http://localhost:3000
organization:
  name: My Org
backend:
  baseUrl: http://localhost:7007
  listen:
    port: 7007
  csp:
    connect-src:
      - "'self'"
      - 'http:'
      - 'https:'
  cors:
    origin: http://localhost:3000
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  database:
    client: better-sqlite3
    connection: ':memory:'
proxy:
  skipInvalidProxies: true
  endpoints: {}
lighthouse:
  baseUrl: temp
dynatrace:
  baseUrl: temp
techdocs:
  builder: external
auth:
  environment: development
  providers:
    guest: {}
catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, Group, Resource, Location, Template, API]
  locations:
    # Note: integrations.github[].apps must be correctly configured to read GitHub locations
    - type: file
      target: ../../catalog-entities/all.yaml
  providers:
    keycloakOrg:
      default:
        baseUrl: http://localhost:8080/
        loginRealm: demo-rhdh-events
        realm: demo-rhdh-events
        clientId: rhdh-events-webhook
        clientSecret: ${CLIENT_SECRET}
        schedule:
          frequency:
            hours: 1
          timeout:
            minutes: 30
          initialDelay:
            seconds: 7
events:
  http:
    topics:
      - keycloak

dynamicPlugins:
          frontend:
            red-hat-developer-hub.backstage-plugin-dynamic-home-page:
              dynamicRoutes:
                - path: /
                  importName: DynamicHomePage
              mountPoints:
                - mountPoint: home.page/cards
                  importName: SearchBar
                  config:
                    layouts:
                      xl: { w: 10, h: 1, x: 1 }
                      lg: { w: 10, h: 1, x: 1 }
                      md: { w: 10, h: 1, x: 1 }
                      sm: { w: 10, h: 1, x: 1 }
                      xs: { w: 12, h: 1 }
                      xxs: { w: 12, h: 1 }
                - mountPoint: home.page/cards
                  importName: QuickAccessCard
                  config:
                    layouts:
                      xl: { w: 7, h: 8 }
                      lg: { w: 7, h: 8 }
                      md: { w: 7, h: 8 }
                      sm: { w: 12, h: 8 }
                      xs: { w: 12, h: 8 }
                      xxs: { w: 12, h: 8 }
                - mountPoint: home.page/cards
                  importName: CatalogStarredEntitiesCard
                  config:
                    layouts:
                      xl: { w: 5, h: 4, x: 7 }
                      lg: { w: 5, h: 4, x: 7 }
                      md: { w: 5, h: 4, x: 7 }
                      sm: { w: 12, h: 4 }
                      xs: { w: 12, h: 4 }
                      xxs: { w: 12, h: 4 }
