app:
  title: Red Hat Developer Hub
  baseUrl: http://localhost:3000
organization:
  name: My Org
backend:
  baseUrl: http://localhost:7007
  listen:
    port: 7007
  csp:
    connect-src:
      - "'self'"
      - 'http:'
      - 'https:'
  cors:
    origin: http://localhost:3000
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  database:
    client: better-sqlite3
    connection: ':memory:'
proxy:
  skipInvalidProxies: true
  endpoints: {}
lighthouse:
  baseUrl: temp
dynatrace:
  baseUrl: temp
techdocs:
  builder: external
auth:
  environment: development
  providers:
    guest: {}
catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, Group, Resource, Location, Template, API]
  locations:
    # Note: integrations.github[].apps must be correctly configured to read GitHub locations
    - type: file
      target: ../../catalog-entities/all.yaml
  providers:
    keycloakOrg:
      default:
        baseUrl: http://localhost:8080/
        loginRealm: demo-rhdh-events
        realm: demo-rhdh-events
        clientId: rhdh-events-webhook
        clientSecret: ${CLIENT_SECRET}
        schedule:
          frequency:
            hours: 1
          timeout:
            minutes: 30
          initialDelay:
            seconds: 7
events:
  http:
    topics:
      - keycloak

